### ISSUE TITLE
Fake DOM ready in NodeJS environment

### ISSUE THREAD

**Issue by FredyC** [ded/domready#34]
I think this is necessary for tests. For now I am running tests using [test'em](https://github.com/airportyh/testem) utility which essentially runs tests in the browser. However when I deploy tests to the CI, my test fails.

It would be nice to incorporate [detection](http://timetler.com/2012/10/13/environment-detection-in-javascript/) of the environment and in case of Node just skip all the _document_ stuff and just use `process.nextTick` to call attached callbacks.

**Comment by jasonkarns** [comment]
This seems like a super old issue but this is what we do:

We are building a library that is both browser and node compatible. We use browserify to build the browser-compatible distributable.

So we have a local module in `lib/domready.js' with contents:

```js
module.exports = process.nextTick;
```

In our code we always require `./lib/domready` which defaults to this module for node. Then we configure browserify to replace `./lib/domready` with `domready` (the npm module) in our package.json:

```json
  "browser": {
    "./lib/domready.js": "domready"
  },
```

Thus, regardless of test or production, the process.nextTick wrapper module is used in node, while this `domready` module is used in the browser.

**Comment by juliangruber** [comment]
+1 to ^
