### ISSUE TITLE
It does not work with jsdom

### ISSUE THREAD

**Issue by ibc** [ded/domready#42]
Even when requiring [jsdom](https://github.com/tmpvar/jsdom), `domready()` fails:

```
xxxxxxnode_modules/domready/ready.js:13
    , doc = document
            ^
ReferenceError: document is not defined
```

I use `jsdom` as follows:

```
var jsdom = require('jsdom').jsdom;

// Define global.window.
global.window = jsdom(undefined).parentWindow;
```

This is enough to make jQuery happy under Node (you can run `$("any-selector")`, but still makes `domready()` to fail.

Does domready expect a global `document` object? Can it be mitigated to work when jsdom is load?

**Comment by RVledder** [comment]
But doesn't jsdom define using globals as an antipattern? 

Source: https://github.com/jsdom/jsdom/wiki/Don't-stuff-jsdom-globals-onto-the-Node-global
